import { Box, Flex, Heading, HStack, Image, Text, VStack } from '@chakra-ui/react';
import Head from 'next/head';
import { Stat } from '../components/Stat';


export default function Home() {
  return (
    <Flex w="100vw" h="100vh" bg="#0a0c1b" align="center" justify="center">
      <Head>
        <title>Stats Preview Card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Flex
        as="main"
        bg="#1c1938"
        color="#f9fbfa"
        rounded="lg"
        maxW={['375px', '1440px']}
        m="4"
      >
        <Flex align="center" p="16">
          <Flex direction="column" maxW="390px" mr="8">

            <Heading fontFamily="Inter">
              Get <Text display="inline-block" color="#b264de">insights</Text> that help your business grow.
            </Heading>
            <Text
              color="#ffffffbf"
              fontSize="15px"
              fontFamily="Lexend Deca"
              mt="6"
            >
              Discover the benefits of data analytics and make better decisions regarding revenue, customer
              experience, and overall efficiency.
            </Text>

            <Flex justify="space-between" mt="20">
              <Stat 
                heading="COMPANIES"
                stat="10k+"
              />
              <Stat 
                heading="TEMPLATES"
                stat="314"
              />
              <Stat 
                heading="QUERIES"
                stat="12M+"
              />
            </Flex>
          </Flex>
        </Flex>
        <Image
          filter="sepia(80%) hue-rotate(230deg) contrast(75%) saturate(6) brightness(0.6)"
          src="/image-header-desktop.jpg"
          alt="Women at workplace"
          objectFit="cover"
          borderRightRadius="lg"
        />
      </Flex>
    </Flex>
  )
}
